In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

irisdata = pd.read_csv(url, names=colnames)

In [4]:
print(irisdata.shape)
print(irisdata.head())

(150, 5)
   sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [5]:
X = irisdata.drop('Class', axis=1)
y = irisdata['Class']

In [6]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [7]:
from sklearn.svm import SVC # "Support Vector Classifier" 
clf = SVC(kernel='linear') 
  
# fitting x samples and y classes 
clf.fit(Xtrain, ytrain) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [10]:
y_pred = clf.predict(Xtest)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(ytest,y_pred))
print(classification_report(ytest,y_pred))

[[ 8  0  0]
 [ 0  7  1]
 [ 0  1 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       0.88      0.88      0.88         8
 Iris-virginica       0.93      0.93      0.93        14

      micro avg       0.93      0.93      0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.93      0.93      0.93        30



In [17]:
#polynomial
clf = SVC(kernel='poly', degree=25) 
  
# fitting x samples and y classes 
clf.fit(Xtrain, ytrain) 
y_pred = clf.predict(Xtest)
print(confusion_matrix(ytest,y_pred))
print(classification_report(ytest,y_pred))

[[ 8  0  0]
 [ 0  7  1]
 [ 0  1 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       0.88      0.88      0.88         8
 Iris-virginica       0.93      0.93      0.93        14

      micro avg       0.93      0.93      0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.93      0.93      0.93        30



C:\Users\attom\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [13]:
#sigmoid
clf = SVC(kernel='sigmoid') 
  
# fitting x samples and y classes 
clf.fit(Xtrain, ytrain) 
y_pred = clf.predict(Xtest)
print(confusion_matrix(ytest,y_pred))
print(classification_report(ytest,y_pred))

[[ 4  4  0]
 [ 7  1  0]
 [14  0  0]]
                 precision    recall  f1-score   support

    Iris-setosa       0.16      0.50      0.24         8
Iris-versicolor       0.20      0.12      0.15         8
 Iris-virginica       0.00      0.00      0.00        14

      micro avg       0.17      0.17      0.17        30
      macro avg       0.12      0.21      0.13        30
   weighted avg       0.10      0.17      0.11        30



C:\Users\attom\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\attom\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [14]:
#Gaussian
clf = SVC(kernel='rbf') 
  
# fitting x samples and y classes 
clf.fit(Xtrain, ytrain) 
y_pred = clf.predict(Xtest)
print(confusion_matrix(ytest,y_pred))
print(classification_report(ytest,y_pred))

[[ 8  0  0]
 [ 0  6  2]
 [ 0  1 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       0.86      0.75      0.80         8
 Iris-virginica       0.87      0.93      0.90        14

      micro avg       0.90      0.90      0.90        30
      macro avg       0.91      0.89      0.90        30
   weighted avg       0.90      0.90      0.90        30



C:\Users\attom\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
